#!/usr/bin/env python3
"""Export raw skill data into a stable, tool-ready layout.

The raw dataset mixes multiple collection batches, annotator folders, hidden
macOS artifacts, and inconsistent JSON file names. This script keeps the raw
dataset intact and writes a normalized view to:

    data/inner_representation/

Output layout:
    data/inner_representation/
      README.md
      index.json
      by_slug.json
      stats.json
      <canonical_id>/
        manifest.json
        SKILL.md
        _meta.json
        primary.json
        classified.json
        classified_version2.json
        human.json
        regex.json

Canonical ids are ASCII-safe. If the same skill slug appears more than once,
the exporter appends a short hash derived from the original relative path.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


IGNORE_DIR_NAMES = {
    "__MACOSX",
    "node_modules",
    "venv",
    ".venv",
    "__pycache__",
}

DOC_ALLOWLIST = (
    "README.md",
    "package.json",
    "requirements.txt",
    "pyproject.toml",
    "Cargo.toml",
)

README_TEXT = """# Tool-ready dataset

This directory is generated by `scripts/export_tool_ready_data.py`.

Use this directory instead of the raw `hot100-300/` tree when an external tool
needs a stable, enumerable dataset layout.

Files:
- `index.json`: full manifest for all exported skills
- `by_slug.json`: raw slug to canonical id mapping
- `stats.json`: export summary
- `<canonical_id>/`: one normalized skill directory

Per-skill files:
- `SKILL.md`: copied from the source skill directory
- `_meta.json`: original metadata if present, otherwise a synthetic fallback
- `primary.json`: preferred JSON view for external tools
- `classified.json`: normalized alias for `*_classified.json`
- `classified_version2.json`: normalized alias for `*_classified_version2.json`
- `human.json`: normalized alias for `*_human_classified.json`
- `regex.json`: normalized alias for `*_正则.json`
- `manifest.json`: per-skill metadata, source mapping, and file inventory

Canonical ids are ASCII-safe. Duplicate raw slugs receive a `--<hash>` suffix.
"""


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    data_root = repo_root / "data"
    return argparse.ArgumentParser(description=__doc__).parse_args(
        namespace=argparse.Namespace(
            source_root=data_root / "hot100-300",
            output_root=data_root / "inner_representation",
            data_root=data_root,
        )
    )


def is_ignored_path(path: Path) -> bool:
    for part in path.parts:
        if part in IGNORE_DIR_NAMES or part.startswith("."):
            return True
    return False


def iter_skill_dirs(source_root: Path) -> list[Path]:
    skill_dirs = []
    for skill_file in sorted(source_root.rglob("SKILL.md")):
        if is_ignored_path(skill_file):
            continue
        skill_dirs.append(skill_file.parent)
    return skill_dirs


def ascii_slug(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", value).strip("-._").lower()
    return cleaned or "skill"


def relpath_from(base: Path, path: Path) -> str:
    return path.relative_to(base).as_posix()


def build_canonical_ids(data_root: Path, skill_dirs: list[Path]) -> dict[Path, str]:
    base_counts = Counter(ascii_slug(path.name) for path in skill_dirs)
    canonical_ids: dict[Path, str] = {}
    for skill_dir in skill_dirs:
        base_slug = ascii_slug(skill_dir.name)
        if base_counts[base_slug] == 1:
            canonical_ids[skill_dir] = base_slug
            continue
        relative = relpath_from(data_root, skill_dir)
        digest = hashlib.sha1(relative.encode("utf-8")).hexdigest()[:8]
        canonical_ids[skill_dir] = f"{base_slug}--{digest}"
    return canonical_ids


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def parse_frontmatter(skill_text: str) -> dict[str, str]:
    if not skill_text.startswith("---\n"):
        return {}
    end = skill_text.find("\n---\n", 4)
    if end == -1:
        return {}
    frontmatter = skill_text[4:end].splitlines()
    parsed: dict[str, str] = {}
    for line in frontmatter:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        parsed[key.strip()] = value.strip().strip('"').strip("'")
    return parsed


def load_json(path: Path) -> tuple[Any | None, str | None]:
    try:
        return json.loads(read_text(path)), None
    except json.JSONDecodeError as exc:
        return None, f"{path.name}: {exc}"


def normalize_json_aliases(skill_dir: Path) -> dict[str, Path]:
    aliases: dict[str, Path] = {}
    for path in sorted(skill_dir.iterdir()):
        if not path.is_file():
            continue
        name = path.name
        if name == "_meta.json":
            continue
        if name.endswith("_classified_version2.json"):
            aliases.setdefault("classified_version2.json", path)
        elif name.endswith("_human_classified.json") or name == "human.json":
            aliases.setdefault("human.json", path)
        elif name.endswith("_classified.json"):
            aliases.setdefault("classified.json", path)
        elif name.endswith("_正则.json"):
            aliases.setdefault("regex.json", path)
    return aliases


def pick_primary_json(aliases: dict[str, Path]) -> tuple[str | None, Path | None]:
    for alias_name in (
        "classified_version2.json",
        "classified.json",
        "human.json",
        "regex.json",
    ):
        path = aliases.get(alias_name)
        if path is not None:
            return alias_name, path
    return None, None


def ensure_clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def write_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def copy_file(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def synthesize_meta(
    existing_meta: dict[str, Any] | None,
    *,
    canonical_id: str,
    raw_slug: str,
    source_relative_path: str,
) -> dict[str, Any]:
    meta = dict(existing_meta or {})
    meta.setdefault("ownerId", None)
    meta.setdefault("slug", raw_slug)
    meta.setdefault("version", None)
    meta.setdefault("publishedAt", None)
    meta["canonicalId"] = canonical_id
    meta["sourceSlug"] = raw_slug
    meta["sourceRelativePath"] = source_relative_path
    meta["synthetic"] = existing_meta is None
    return meta


def export_dataset(source_root: Path, output_root: Path, data_root: Path) -> dict[str, Any]:
    skill_dirs = iter_skill_dirs(source_root)
    canonical_ids = build_canonical_ids(data_root, skill_dirs)

    ensure_clean_dir(output_root)
    (output_root / "README.md").write_text(README_TEXT, encoding="utf-8")

    entries: list[dict[str, Any]] = []
    by_slug: dict[str, list[str]] = defaultdict(list)
    invalid_json_files: list[str] = []
    synthetic_meta_count = 0
    primary_json_count = 0
    duplicate_slug_count = len(skill_dirs) - len({path.name for path in skill_dirs})

    for skill_dir in skill_dirs:
        canonical_id = canonical_ids[skill_dir]
        entry_dir = output_root / canonical_id
        entry_dir.mkdir(parents=True, exist_ok=True)

        source_relative_path = relpath_from(data_root, skill_dir)
        dataset_relative_path = relpath_from(source_root, skill_dir)
        parent_chain = list(Path(dataset_relative_path).parts[:-1])
        raw_slug = skill_dir.name

        skill_text = read_text(skill_dir / "SKILL.md")
        frontmatter = parse_frontmatter(skill_text)
        copy_file(skill_dir / "SKILL.md", entry_dir / "SKILL.md")

        meta_payload: dict[str, Any] | None = None
        meta_path = skill_dir / "_meta.json"
        if meta_path.exists():
            loaded_meta, error = load_json(meta_path)
            if error is not None:
                invalid_json_files.append(f"{source_relative_path}/{meta_path.name}")
            if isinstance(loaded_meta, dict):
                meta_payload = loaded_meta
        if meta_payload is None:
            synthetic_meta_count += 1
        normalized_meta = synthesize_meta(
            meta_payload,
            canonical_id=canonical_id,
            raw_slug=raw_slug,
            source_relative_path=source_relative_path,
        )
        write_json(entry_dir / "_meta.json", normalized_meta)

        aliases = normalize_json_aliases(skill_dir)
        normalized_files: dict[str, str] = {"SKILL.md": "SKILL.md", "_meta.json": "_meta.json"}

        for alias_name, src in aliases.items():
            loaded_payload, error = load_json(src)
            if error is not None:
                invalid_json_files.append(f"{source_relative_path}/{src.name}")
                copy_file(src, entry_dir / alias_name)
            else:
                write_json(entry_dir / alias_name, loaded_payload)
            normalized_files[alias_name] = alias_name

        primary_alias, primary_src = pick_primary_json(aliases)
        if primary_alias is not None and primary_src is not None:
            loaded_payload, error = load_json(primary_src)
            if error is not None:
                invalid_json_files.append(f"{source_relative_path}/{primary_src.name}")
                copy_file(primary_src, entry_dir / "primary.json")
            else:
                write_json(entry_dir / "primary.json", loaded_payload)
            normalized_files["primary.json"] = "primary.json"
            primary_json_count += 1

        copied_docs = []
        for doc_name in DOC_ALLOWLIST:
            doc_path = skill_dir / doc_name
            if doc_path.exists():
                copy_file(doc_path, entry_dir / doc_name)
                copied_docs.append(doc_name)
                normalized_files[doc_name] = doc_name

        manifest = {
            "canonicalId": canonical_id,
            "rawSlug": raw_slug,
            "name": frontmatter.get("name", raw_slug),
            "description": frontmatter.get("description", ""),
            "sourceRelativePath": source_relative_path,
            "sourceDatasetPath": dataset_relative_path,
            "sourceParents": parent_chain,
            "primaryJson": "primary.json" if primary_alias is not None else None,
            "primaryJsonSource": primary_src.name if primary_src is not None else None,
            "files": normalized_files,
            "copiedDocs": copied_docs,
            "sourceTopLevelFiles": sorted(
                [path.name for path in skill_dir.iterdir() if path.is_file() and not path.name.startswith(".")]
            ),
            "syntheticMeta": normalized_meta.get("synthetic", False),
        }
        write_json(entry_dir / "manifest.json", manifest)
        normalized_files["manifest.json"] = "manifest.json"

        entry = {
            "canonicalId": canonical_id,
            "rawSlug": raw_slug,
            "name": manifest["name"],
            "description": manifest["description"],
            "sourceRelativePath": source_relative_path,
            "sourceDatasetPath": dataset_relative_path,
            "sourceParents": parent_chain,
            "primaryJson": manifest["primaryJson"],
            "files": normalized_files,
            "syntheticMeta": manifest["syntheticMeta"],
        }
        entries.append(entry)
        by_slug[raw_slug].append(canonical_id)

    entries.sort(key=lambda item: item["canonicalId"])
    ordered_by_slug = {slug: sorted(ids) for slug, ids in sorted(by_slug.items())}
    stats = {
        "sourceRoot": relpath_from(data_root.parent, source_root),
        "outputRoot": relpath_from(data_root.parent, output_root),
        "skillCount": len(entries),
        "slugCount": len(ordered_by_slug),
        "duplicateSlugCount": duplicate_slug_count,
        "syntheticMetaCount": synthetic_meta_count,
        "primaryJsonCount": primary_json_count,
        "invalidJsonCount": len(invalid_json_files),
        "invalidJsonFiles": sorted(set(invalid_json_files)),
    }

    write_json(output_root / "index.json", entries)
    write_json(output_root / "by_slug.json", ordered_by_slug)
    write_json(output_root / "stats.json", stats)
    return stats


def main() -> int:
    args = parse_args()
    stats = export_dataset(args.source_root, args.output_root, args.data_root)
    print(json.dumps(stats, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
